### ISSUE TITLE
Where is the paper?

### ISSUE THREAD

**Issue by Ostnie** [halwai/bird_classification#11]
Could you please tell me the paper you read about this code ? I want to learn some details,thank you!

**Comment by halwai** [comment]
Thanks for your interest and sorry for my late reply. 
I have refereed to the following paper (though this paper is for generic image classifciation). 
VGG-   https://arxiv.org/pdf/1409.1556.pdf
AlexNet/CaffeeNet -https://papers.nips.cc/paper/4824-imagenet-classification-with-deep-convolutional-neural-networks.pdf
